proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: scientists
  container-wait-time: 60000
  # Example: 'simple' authentication configuration
  users:
  - name: jack
    password: password
    groups: scientists
  - name: jeff
    password: password
    groups: mathematicians
  specs:
    - id: pgadmin
      container-image: dpage/pgadmin4:latest
      port: 80
      target-path: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"
      container-env:
        SCRIPT_NAME: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH').replaceFirst('/$','')}"
        PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
        PGADMIN_CONFIG_SERVER_MODE: "False"
        PGADMIN_DEFAULT_EMAIL: "user@example.com"
        PGADMIN_DEFAULT_PASSWORD: "password"
logging:
  file:
    name: shinyproxy.log
